-- --------------------------------------------------
-- AUTHOER: VAISHNAV DATIR
-- --------------------------------------------------

CREATE TABLE T_STUDENTS (
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    GENDER VARCHAR(45),
    GRADE VARCHAR(10),
    EMAIL VARCHAR(100),
    ROLL_NO VARCHAR(20) UNIQUE,
    UPDATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE T_VACCINATION_DRIVES (
    DRIVE_ID INT AUTO_INCREMENT PRIMARY KEY,
    VACCINE_NAME VARCHAR(100),
    START_DATE DATE,  -- START DATE OF THE VACCINATION DRIVE
    END_DATE DATE,    -- END DATE OF THE VACCINATION DRIVE
    AVAILABLE_DOSES INT,
    GRADE_ELIGIBILITY VARCHAR(50),
    UPDATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE T_STUDENT_VACCINATION_RECORDS (
    RECORD_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT,  -- LINK TO THE STUDENT TABLE
    DRIVE_ID INT,    -- LINK TO THE VACCINATION_DRIVES TABLE
    VACCINATION_DATE DATE,
    DOSE_NUMBER INT,
    STATUS VARCHAR(20),
    UPDATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (STUDENT_ID) REFERENCES T_STUDENTS(STUDENT_ID),
    FOREIGN KEY (DRIVE_ID) REFERENCES T_VACCINATION_DRIVES(DRIVE_ID)
);
